using ROS.Game.Core;
using UnityEngine;

namespace ROS.Game.Weapons
{
    [CreateAssetMenu(menuName = "ROS/Weapons/Weapon Definition", fileName = "Weapon_")]
    public sealed class WeaponDefinition :
        ScriptableObject,
        IGameDataDefinition
    {
        [Header("Identity")]
        public string weaponId = "rifle_001";
        public string displayName = "Prototype Rifle";
        public WeaponFamily family = WeaponFamily.AssaultRifle;
        public AmmoType ammoType = AmmoType.Rifle;
        public WeaponFireMode fireMode = WeaponFireMode.Auto;

        [Header("Fire Modes")]
        public bool supportsSingle = true;
        public bool supportsBurst;
        public bool supportsAuto = true;

        [Header("Data Provenance")]
        public DataConfidence dataConfidence =
            DataConfidence.Prototype;

        [Header("Ballistics")]
        [Min(1f)] public float damage = 28f;
        [Min(0.01f)] public float shotsPerSecond = 9f;
        [Min(1f)] public float range = 250f;
        [Min(1)] public int projectilesPerShot = 1;

        [Header("Impact Feedback")]
        [Min(0.05f)] public float impactScale = 1f;
        [Min(0.05f)] public float bulletHoleScale = 1f;
        [Min(0.001f)] public float tracerWidth = 0.012f;

        [Header("Ammo")]
        [Min(1)] public int magazineSize = 30;
        [Min(0)] public int startingReserveAmmo = 90;
        [Min(0.1f)] public float reloadTime = 2.2f;
        [Min(0.1f)] public float emptyReloadTime = 2.7f;
        [Min(1)] public int burstCount = 3;

        [Header("Recoil")]
        [Min(0f)] public float verticalRecoil = 1.2f;
        [Min(0f)] public float horizontalRecoil = 0.35f;
        [Min(0f)] public float recoilReturnSpeed = 8f;
        [Min(0f)] public float recoilSnappiness = 14f;

        [Header("Accuracy - Base")]
        [Tooltip("Spread when firing without aiming.")]
        [Min(0f)] public float hipSpreadDegrees = 1.35f;
        [Tooltip("Spread while aiming down sights / over shoulder.")]
        [Min(0f)] public float adsSpreadDegrees = 0.28f;

        [Header("Accuracy - Movement Multipliers")]
        [Min(0f)] public float walkSpreadMultiplier = 1.25f;
        [Min(0f)] public float runSpreadMultiplier = 1.65f;
        [Min(0f)] public float sprintSpreadMultiplier = 2.4f;
        [Min(0f)] public float crouchSpreadMultiplier = 0.72f;
        [Min(0f)] public float airborneSpreadMultiplier = 2.75f;

        [Header("Accuracy - Sustained Fire")]
        [Tooltip("Additional spread added after every shot in a burst.")]
        [Min(0f)] public float spreadBloomPerShot = 0.10f;
        [Tooltip("Maximum extra spread generated by sustained fire.")]
        [Min(0f)] public float maxSpreadBloom = 1.2f;
        [Tooltip("Degrees of bloom recovered per second when not firing.")]
        [Min(0f)] public float spreadRecoveryPerSecond = 3.5f;

        // Kept for compatibility with older assets/tools. New combat code uses
        // hipSpreadDegrees and adsSpreadDegrees instead.
        [HideInInspector] public float spreadDegrees = 0.9f;

        public string StableId => weaponId;

        public DataConfidence Confidence =>
            dataConfidence;

        public bool SupportsFireMode(
            WeaponFireMode mode
        )
        {
            return mode switch
            {
                WeaponFireMode.Single => supportsSingle,
                WeaponFireMode.Burst => supportsBurst,
                WeaponFireMode.Auto => supportsAuto,
                _ => false
            };
        }

        public WeaponFireMode GetInitialFireMode()
        {
            if (SupportsFireMode(fireMode))
            {
                return fireMode;
            }

            if (supportsSingle)
            {
                return WeaponFireMode.Single;
            }

            if (supportsBurst)
            {
                return WeaponFireMode.Burst;
            }

            return WeaponFireMode.Auto;
        }

        public WeaponFireMode GetNextFireMode(
            WeaponFireMode current
        )
        {
            WeaponFireMode[] orderedModes =
            {
                WeaponFireMode.Single,
                WeaponFireMode.Burst,
                WeaponFireMode.Auto
            };

            int currentIndex =
                System.Array.IndexOf(
                    orderedModes,
                    current
                );

            for (int offset = 1; offset <= orderedModes.Length; offset++)
            {
                int index =
                    (currentIndex + offset + orderedModes.Length) %
                    orderedModes.Length;

                if (SupportsFireMode(orderedModes[index]))
                {
                    return orderedModes[index];
                }
            }

            return GetInitialFireMode();
        }

        public float GetReloadDuration(
            bool emptyMagazine
        )
        {
            return emptyMagazine
                ? Mathf.Max(reloadTime, emptyReloadTime)
                : reloadTime;
        }

        public int GetProjectileCount()
        {
            return Mathf.Max(1, projectilesPerShot);
        }
    }
}
