using ROS.Game.Core;
using UnityEngine;

namespace ROS.Game.Weapons
{
    [CreateAssetMenu(menuName = "ROS/Weapons/Weapon Definition", fileName = "Weapon_")]
    public sealed class WeaponDefinition : ScriptableObject
    {
        [Header("Identity")]
        public string weaponId = "rifle_001";
        public string displayName = "Prototype Rifle";
        public WeaponFireMode fireMode = WeaponFireMode.Auto;

        [Header("Ballistics")]
        [Min(1f)] public float damage = 28f;
        [Min(0.01f)] public float shotsPerSecond = 9f;
        [Min(1f)] public float range = 250f;

        [Header("Ammo")]
        [Min(1)] public int magazineSize = 30;
        [Min(0.1f)] public float reloadTime = 2.2f;
        [Min(1)] public int burstCount = 3;

        [Header("Accuracy - Base")]
        [Tooltip("Spread when firing without aiming.")]
        [Min(0f)] public float hipSpreadDegrees = 1.35f;
        [Tooltip("Spread while aiming down sights / over shoulder.")]
        [Min(0f)] public float adsSpreadDegrees = 0.28f;

        [Header("Accuracy - Movement Multipliers")]
        [Min(0f)] public float walkSpreadMultiplier = 1.25f;
        [Min(0f)] public float runSpreadMultiplier = 1.65f;
        [Min(0f)] public float sprintSpreadMultiplier = 2.4f;
        [Min(0f)] public float crouchSpreadMultiplier = 0.72f;
        [Min(0f)] public float airborneSpreadMultiplier = 2.75f;

        [Header("Accuracy - Sustained Fire")]
        [Tooltip("Additional spread added after every shot in a burst.")]
        [Min(0f)] public float spreadBloomPerShot = 0.10f;
        [Tooltip("Maximum extra spread generated by sustained fire.")]
        [Min(0f)] public float maxSpreadBloom = 1.2f;
        [Tooltip("Degrees of bloom recovered per second when not firing.")]
        [Min(0f)] public float spreadRecoveryPerSecond = 3.5f;

        // Kept for compatibility with older assets/tools. New combat code uses
        // hipSpreadDegrees and adsSpreadDegrees instead.
        [HideInInspector] public float spreadDegrees = 0.9f;
    }
}
